#include "Commands.h"
#include <assert.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include "ADTs/AVLTree.h"
#include "ADTs/BinarySearchTree.h"
#include "ADTs/SplayTree.h"
#include "Util.h"

void runHelp() {
    char* subcommand = strtok(NULL, " \n");
    if (!subcommand) {
        printf("[INFO] Printing command list:\n");
        for (int i = 0; i < COMMAND_NUMBER; i++) {
            printf("%2d. ", i + 1);
            printCommandFormat((Command)i);
        }
        printf("\n");
        printf("Use \"help <command>\" command to get more detail.\n");
        return;
    }

    printf("[WARNING] Some mannuals is generated by AI\n");
    char filePath[] = "Manuls/";
    strcat(filePath, reverseHashCommand(hashCommand(subcommand)));
    strcat(filePath, ".txt");
    FILE* manul = fopen(filePath, "r");
    if (!manul) {
        printf("[ERROR] Manul not found.\n");
        return;
    }
    char buffer[1000];
    while (fgets(buffer, 1000, manul)) {
        printf("%s", buffer);
    }
    fclose(manul);
    printf("\n");
}

static void AVLInOrderTraversal(AVLTreeADT t) {
    if (t == NULL) return;
    AVLInOrderTraversal(t->lst);
    printf("%d ", GetNodeValue(t->rt));
    AVLInOrderTraversal(t->rst);
}

static void AVLPreOrderTraversal(AVLTreeADT t) {
    if (t == NULL) return;
    printf("%d ", GetNodeValue(t->rt));
    AVLPreOrderTraversal(t->lst);
    AVLPreOrderTraversal(t->rst);
}

static void AVLPostOrderTraversal(AVLTreeADT t) {
    if (t == NULL) return;
    AVLPostOrderTraversal(t->lst);
    AVLPostOrderTraversal(t->rst);
    printf("%d ", GetNodeValue(t->rt));
}

void runTraversal(TreePtr trees[]) {
    char* subcommand1 = strtok(NULL, " \n");
    char* subcommand2 = strtok(NULL, " \n");
    if (!subcommand1 || !subcommand2) {
        printf("[ERROR] Insufficient argument.\n");
        printCommandFormat(TRAVERSAL);
        return;
    }
    int index;
    if (!sscanf(subcommand1, "%d", &index)) {
        printf("[ERROR] Invalid argument.\n");
        printCommandFormat(TRAVERSAL);
        return;
    }

    printf("[INFO] Traversing Tree(%d) in ", index);
    switch (hashSubcommand(subcommand2)) {
        case IN_ORDER:
            printf("in-order.\n");
            switch (trees[index]->type) {
                case AVL:
                    AVLInOrderTraversal(trees[index]->root);
                    break;
                case BST:
                    todo("BST traversal");
                    break;
                case SPL:
                    todo("SPL traversal");
                    break;
                default:
                    assert(false && "UNREACHABLE");
                    break;
            }
            break;
        case PRE_ORDER:
            printf("pre-order.\n");
            switch (trees[index]->type) {
                case AVL:
                    AVLPreOrderTraversal(trees[index]->root);
                    break;
                case BST:
                    todo("BST traversal");
                    break;
                case SPL:
                    todo("SPL traversal");
                    break;
                default:
                    assert(false && "UNREACHABLE");
                    break;
            }
            break;
        case POST_ORDER:
            printf("post-order.\n");
            switch (trees[index]->type) {
                case AVL:
                    AVLPostOrderTraversal(trees[index]->root);
                    break;
                case BST:
                    todo("BST traversal");
                    break;
                case SPL:
                    todo("SPL traversal");
                    break;
                default:
                    assert(false && "UNREACHABLE");
                    break;
            }
            break;
        default:
            printf("[ERROR] Invalid argument.\n");
            printf("Format: [t]raversal <type:[in]-order | [pre]-order | [post]-order>\n");
            break;
    }
    printf("\n");
}

void runInsert(TreePtr trees[]) {
    int index, val;
    if (!readAndParseSubcommandToInt(&index, INSERT) || !readAndParseSubcommandToInt(&val, INSERT)) {
        return;
    }

    if (index >= MAX_TREE_NUMBER) {
        printf("[ERROR] Index is too large.\n");
        printf("Enter a number less than %d.\n", MAX_TREE_NUMBER);
        return;
    }
    if (trees[index] == NULL) {
        printf("[ERROR] Inserting to uninitialized tree.\n");
        printf("Run new command first.\n");
        return;
    }

    assert(TREE_TYPE_NUMBER == 3);
    switch (trees[index]->type) {
        case AVL:
            trees[index]->root = AVLInsertNode(NewTreeNode(val), trees[index]->root);
            printf("[INFO] TreeNode(%d) inserted in Tree(%d).\n", val, index);
            break;
        case BST:
            trees[index]->root = InsertNode(trees[index]->root, NewTreeNode(val));
            printf("[INFO] TreeNode(%d) inserted in Tree(%d).\n", val, index);
            break;
        case SPL:
            trees[index]->root = Splay_Insert(trees[index]->root, val);
            printf("[INFO] TreeNode(%d) inserted in Tree(%d).\n", val, index);
            break;
        default:
            assert(false && "[ERROR] UNREACHABLE\n");
            break;
    }
}

void runInsertMany(TreePtr trees[]) {
    int index, count;
    if (!readAndParseSubcommandToInt(&index, INSERT_MANY) || !!readAndParseSubcommandToInt(&count, INSERT_MANY)) {
        return;
    }

    if (index >= MAX_TREE_NUMBER) {
        printf("[ERROR] Index is too large.\n");
        printf("Enter a number less than %d.\n", MAX_TREE_NUMBER);
        return;
    }
    if (trees[index] == NULL) {
        printf("[ERROR] Inserting to uninitialized tree.\n");
        printf("Run new command first.\n");
        return;
    }
    if (count > 100) {
        printf("[ERROR] Count is too large.\n");
        printf("Input a number less than 100.\n");
        return;
    }
    int arr[100] = {0}, i = 0;
    char* subcommand;
    while ((subcommand = strtok(NULL, " \n"))) {
        sscanf(subcommand, "%d", &arr[i]);
        i++;
    }
    if (i < count) {
        printf("[ERROR] Insufficient argument.\n");
        printCommandFormat(INSERT_MANY);
        return;
    }

    assert(TREE_TYPE_NUMBER == 3);
    switch (trees[index]->type) {
        case AVL:
            for (int i = 0; i < count; i++) {
                trees[index]->root = AVLInsertNode(NewTreeNode(arr[i]), trees[index]->root);
            }
            break;
        case BST:
            for (int i = 0; i < count; i++) {
                trees[index]->root = InsertNode(trees[index]->root, NewTreeNode(arr[i]));
            }
            break;
        case SPL:
            for (int i = 0; i < count; i++) {
                trees[index]->root = Splay_Insert(trees[index]->root, arr[i]);
            }
            break;
        default:
            assert(false && "[ERROR] UNREACHABLE\n");
            break;
    }
    printf("[INFO] %d node(s) inserted in Tree(%d).\n", count, index);
}

char buffer[1024] = {0};

static void AVL_print_node(AVLTreeADT t, FILE* o) {
    fprintf(o, "%s+-%d\n", buffer, t->rt->value);
}

static void AVL_print_subtree(AVLTreeADT t,
                              FILE* o,
                              const char* prf_right,
                              const char* prf_left,
                              char* buf, int buf_sz) {
    if (t->rst) {
        int res = snprintf(buf, buf_sz, "%s", prf_right);
        AVL_print_subtree(t->rst, o, "  ", "| ", buf + res, buf_sz - res);
        *buf = '\0';
    }
    AVL_print_node(t, o);
    if (t->lst) {
        int res = snprintf(buf, buf_sz, "%s", prf_left);
        AVL_print_subtree(t->lst, o, "| ", "  ", buf + res, buf_sz - res);
        *buf = '\0';
    }
}

static void BST_print_node(BinaryTreeADT t, FILE* o) {
    fprintf(o, "%s+-%d\n", buffer, t->rt->value);
}

static void BST_print_subtree(BinaryTreeADT t,
                              FILE* o,
                              const char* prf_right,
                              const char* prf_left,
                              char* buf, int buf_sz) {
    if (t->rst) {
        int res = snprintf(buf, buf_sz, "%s", prf_right);
        BST_print_subtree(t->rst, o, "  ", "| ", buf + res, buf_sz - res);
        *buf = '\0';
    }
    BST_print_node(t, o);
    if (t->lst) {
        int res = snprintf(buf, buf_sz, "%s", prf_left);
        BST_print_subtree(t->lst, o, "| ", "  ", buf + res, buf_sz - res);
        *buf = '\0';
    }
}

static void SPL_print_node(SplayTreeADT t, FILE* o) {
    fprintf(o, "%s+-%d\n", buffer, t->val);
}

static void SPL_print_subtree(SplayTreeADT t,
                              FILE* o,
                              const char* prf_right,
                              const char* prf_left,
                              char* buf, int buf_sz) {
    if (t->r) {
        int res = snprintf(buf, buf_sz, "%s", prf_right);
        SPL_print_subtree(t->r, o, "  ", "| ", buf + res, buf_sz - res);
        *buf = '\0';
    }
    SPL_print_node(t, o);
    if (t->l) {
        int res = snprintf(buf, buf_sz, "%s", prf_left);
        SPL_print_subtree(t->l, o, "| ", "  ", buf + res, buf_sz - res);
        *buf = '\0';
    }
}

void runPrint(TreePtr trees[]) {
    int index;
    if (!readAndParseSubcommandToInt(&index, PRINT)) return;
    if (index >= MAX_TREE_NUMBER) {
        printf("[ERROR] Index is too large.\n");
        printf("Enter a number less than %d.\n", MAX_TREE_NUMBER);
        return;
    }
    if (trees[index] == NULL) {
        printf("[ERROR] Printing uninitialized tree.\n");
        return;
    }

    printf("[INFO] Printing Tree(%d):\n", index);
    assert(TREE_TYPE_NUMBER == 3 && "HAVE NOT EXHAUST ALL TREE TYPES");
    switch (trees[index]->type) {
        case AVL:
            if (trees[index]->root == NULL)
                printf("(NULL)\n");
            else
                AVL_print_subtree(trees[index]->root, stdout, "  ", "  ", buffer, sizeof buffer);
            break;
        case BST:
            if (trees[index]->root == NULL)
                printf("(NULL)\n");
            else
                BST_print_subtree(trees[index]->root, stdout, "  ", "  ", buffer, sizeof buffer);
            break;
        case SPL:
            if (trees[index]->root == NULL)
                printf("(NULL)\n");
            else
                SPL_print_subtree(trees[index]->root, stdout, "  ", "  ", buffer, sizeof buffer);
            break;
        default:
            break;
    }
}

void runDelete(TreePtr trees[]) {
    int index, val;
    if (!readAndParseSubcommandToInt(&index, DELETE) || !readAndParseSubcommandToInt(&val, DELETE)) return;

    if (index >= MAX_TREE_NUMBER) {
        printf("[ERROR] Index is too large.\n");
        printf("Enter a number less than %d.\n", MAX_TREE_NUMBER);
        return;
    }
    if (trees[index] == NULL) {
        printf("[ERROR] Deleteing node from uninitialized tree.\n");
        printf("Run new command first.\n");
        return;
    }

    assert(TREE_TYPE_NUMBER == 3 && "HAVE NOT EXHAUST ALL TREE TYPES");
    switch (trees[index]->type) {
        case AVL:
            todo("AVL delete function");
            break;
        case BST:
            if (!IsNodeExist(trees[index]->root, val)) {
                printf("[ERROR] Deleting non-existent node.\n");
                return;
            }
            trees[index]->root = DeleteNode(trees[index]->root, val);
            printf("[INFO] TreeNode(%d) deleted in Tree(%d).\n", val, index);
            break;
        case SPL:
            todo("AVL delete function");
            break;
        default:
            assert(false && "[ERROR] UNREACHABLE\n");
            break;
    }
}

void runNew(TreePtr trees[]) {
    int index;
    TreeType treeType;
    
    if (!readAndParseSubcommandToInt(&index, NEW)) return;
    if(!readAndParseSubcommandToTreeType(&treeType, NEW)) return;

    if (index >= MAX_TREE_NUMBER) {
        printf("[ERROR] Index is too large.\n");
        printf("Enter a number less than %d.\n", MAX_TREE_NUMBER);
        return;
    }
    switch (treeType) {
        case AVL:
            trees[index] = (TreePtr)malloc(sizeof(Tree));
            trees[index]->type = AVL;
            trees[index]->root = EmptyAVLTree();
            break;
        case BST:
            trees[index] = (TreePtr)malloc(sizeof(Tree));
            trees[index]->type = BST;
            trees[index]->root = EmptyBinaryTree();
            break;
        case SPL:
            trees[index] = (TreePtr)malloc(sizeof(Tree));
            trees[index]->type = SPL;
            trees[index]->root = NULL;
            break;
        default:
            assert(false && "UNREACHABLE");
            return;
    }
    printf("[INFO] A new %s labeled as index %d is created.\n", reverseHashTreeType(treeType), index);
}

void runDumpTrees(TreePtr trees[]) {
    printf("[INFO] Printing all tree info:\n");
    for (int i = 0; i < MAX_TREE_NUMBER; i++) {
        if (trees[i] == NULL)
            printf("Trees[%d] is uninitialized.\n", i);
        else
            printf("Trees[%d] is a %s with root %p\n", i, reverseHashTreeType(trees[i]->type), trees[i]->root);
    }
}

void runSearch(TreePtr trees[]) {
    int index, val;
    if (!readAndParseSubcommandToInt(&index, SEARCH) || !readAndParseSubcommandToInt(&val, SEARCH)) return;
    if (index >= MAX_TREE_NUMBER) {
        printf("[ERROR] Index is too large.\n");
        printf("Enter a number less than %d.\n", MAX_TREE_NUMBER);
        return;
    }
    if (trees[index] == NULL) {
        printf("[ERROR] Searching node from uninitialized tree.\n");
        printf("Run new command first.\n");
        return;
    }

    bool found;
    switch (trees[index]->type) {
        case BST:
            found = IsNodeExist(trees[index]->root, val);
            break;
        case AVL:
            found = AVL_IsNodeExist(trees[index]->root, val);
            break;
        case SPL:
            trees[index]->root = Splay_Find(trees[index]->root, val, &found);
            break;

        default:
            break;
    }
    if (found)
        printf("[INFO] Node(%d) exists in Tree(%d)\n", val, index);
    else
        printf("[INFO] Node(%d) does not exist in Tree(%d)\n", val, index);
}

void runLoadTree(TreePtr trees[]) {
    int index, count;
    TreeType treeType;

    if (!readAndParseSubcommandToInt(&index, LOAD_TREE)) return;
    if (!readAndParseSubcommandToTreeType(&treeType, LOAD_TREE)) {
        return;
    }
    if (!readAndParseSubcommandToInt(&count, LOAD_TREE)) return;
    if (index >= MAX_TREE_NUMBER) {
        printf("[ERROR] Index is too large.\n");
        printf("Enter a number less than %d.\n", MAX_TREE_NUMBER);
        return;
    }
    if (trees[index] != NULL) {
        printf("[ERROR] Loading to occupied tree.\n");
        printf("Run dump_trees to see more details.");
        return;
    }
    if (count > 100) {
        printf("[ERROR] Count is too large.\n");
        printf("Input a number less than 100.\n");
        return;
    }

    char* subcommand;
    int arr[100] = {0}, i = 0;
    while ((subcommand = strtok(NULL, " \n"))) {
        sscanf(subcommand, "%d", &arr[i]);
        i++;
    }
    if (i < count) {
        printf("[ERROR] Insufficient argument.\n");
        printCommandFormat(LOAD_TREE);
        return;
    }

    trees[index] = malloc(sizeof(TreePtr));
    trees[index]->type = treeType;

    switch (trees[index]->type) {
        case AVL:
            printf("[WARNING] load_tree is deprecated for AVL tree.\n");
            printf("Run insert_many instead.\n");
            break;
        case BST:
            todo("BST load_tree");
            break;
        case SPL:
            SplayTreeADT nodes[100] = {NULL};
            for (int i = 0; i < count; i++) {
                if (arr[i] != -1) {
                    nodes[i] = malloc(sizeof(*nodes[i]));
                    nodes[i]->val = arr[i];
                    nodes[i]->l = nodes[i]->r = nodes[i]->p = NULL;

                    if (i > 0) {
                        int pIndex = (i - 1) / 2;
                        nodes[i]->p = nodes[pIndex];
                        if (i % 2 == 1)
                            nodes[pIndex]->l = nodes[i];
                        else
                            nodes[pIndex]->r = nodes[i];
                    }
                }
            }
            trees[index]->root = nodes[0];
            break;

        default:
            assert(false && "UNREACHABLE");
            break;
    }
}